---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: pacman
  namespace: pacman
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - pacman

---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  annotations:
    apps.open-cluster-management.io/reconcile-rate: medium
  name: pacman-acm
  namespace: pacman-acm
spec:
  type: Git
  pathname: 'https://github.com/gmidha1/application-samples'

---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: rdrtest
    apps.open-cluster-management.io/git-path: pacman
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: pacman
  name: pacman-subscription-1
  namespace: pacman
spec:
  channel: pacman-acm/pacman-acm
  placement:
    placementRef:
      kind: PlacementRule
      name: pacman-placement-1

---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  labels:
    app: pacman
  annotations:
  name: pacman-placement-1
  namespace: pacman
spec:
  clusterSelector: {}
  schedulerName: ramen
