clusterGroup:
  name: resilient
  isHubCluster: false

  projects:
  - opp

  namespaces:
    - stackrox
    - openshift-storage

  subscriptions:
    odf:
      name: odf-operator
      namespace: openshift-storage

  applications:
    storage:
      name: storage
      namespace: openshift-storage
      project: opp
      path: charts/hub/odf
