---
global:
  regionalDR:
    - name: regional-setup
      primary:
        name: vp-primary
        s3CompatibleEndpoint: https://s3.ca-central-1.amazonaws.com
        region: primary

      secondaries:
        - name: vp-secondary
          s3CompatibleEndpoint: https://s3.ca-central-1.amazonaws.com
          region: secondary

      secretStore:
        name: vault-backend
        kind: ClusterSecretStore

  pattern: multicluster-devsecops

  cicd:
    namespace: devsecops-ci

  options:
    useCSV: false
    syncPolicy: Automatic
    installPlanApproval: Automatic

  secure-registry:
    namespace: "openshift-storage"

  imageregistry:
    account: PLAINTEXT
    hostname: quay.io
    type: quay

  git:
    hostname: github.com
    account: PLAINTEXT
    username: PLAINTEXT
    email: SOMEWHERE@EXAMPLE.COM
    dev_revision: main

  quay:
    # Needs to be set consistently between hub and spoke clusters
    # TODO: Move back to the hub chart, store in a configmap, have an ACM policy distribute to spoke clusters, have spoke look up from configmap
    org:
      name: devel
      email: devel@myorg.com
    repo: example
  opp: false

main:
  clusterGroupName: hub
