regionalDR:
  - name: regional-setup
    globalnetEnabled: true # Warning! Enable this feature if your clusters have overlapping CIDR blocks
    primary: primary-name
    secondaries:
      - first-secondary
