{{- range .Values.regionalDR }}
{{ $clusterSet := .name }}
{{- range .clusters }}
{{ $cluster := . }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ $cluster.name }}

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $cluster.name }}-cluster-private-key
  namespace: {{ $cluster.name }}
spec:
  dataFrom:
    - extract:
        conversionStrategy: Default
        decodingStrategy: None
        key: secret/hub/privatekey
        metadataPolicy: None
  refreshInterval: 24h0m0s
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: {{ $cluster.name }}-cluster-private-key
    template:
      engineVersion: v2
      mergePolicy: Replace
      type: Opaque

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $cluster.name }}-cluster-pull-secret
  namespace: {{ $cluster.name }}
spec:
  dataFrom:
    - extract:
        conversionStrategy: Default
        decodingStrategy: None
        key: secret/hub/openshiftPullSecret
        metadataPolicy: None
  refreshInterval: 24h0m0s
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: {{ $cluster.name }}-cluster-pull-secret
    template:
      engineVersion: v2
      mergePolicy: Replace
      type: Opaque

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $cluster.name }}-cluster-aws-creds
  namespace: {{ $cluster.name }}
spec:
  dataFrom:
    - extract:
        conversionStrategy: Default
        decodingStrategy: None
        key: secret/hub/aws
        metadataPolicy: None
  refreshInterval: 24h0m0s
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: {{ $cluster.name }}-cluster-aws-creds
    template:
      engineVersion: v2
      mergePolicy: Replace
      type: Opaque

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $cluster.name }}-cluster-install-config
  namespace: {{ $cluster.name }}
type: Opaque
data:
  install-config.yaml: {{ toYaml $cluster.install_config | b64enc }}

---
apiVersion: hive.openshift.io/v1
kind: ClusterDeployment
metadata:
  name: {{ $cluster.name }}
  namespace: {{ $cluster.name }}
  labels:
    purpose: regionalDR
    vendor: OpenShift
    cluster.open-cluster-management.io/clusterset: {{ $clusterSet }}
spec:
  baseDomain: {{ $cluster.install_config.baseDomain }}
  clusterName: {{ $cluster.name }}
  installAttemptsLimit: 1
  installed: false
  platform:
{{- if $cluster.install_config.platform.aws }}
    aws:
      credentialsSecretRef:
        name: {{ $cluster.name }}-cluster-aws-creds
      region: {{ $cluster.install_config.platform.aws.region }}
{{- end }}
  provisioning:
    installConfigSecretRef:
      name: {{ $cluster.name }}-cluster-install-config
    sshPrivateKeySecretRef:
      name: {{ $cluster.name }}-cluster-private-key
    imageSetRef:
      name: img{{ $cluster.version }}-multi-appsub
  pullSecretRef:
    name: {{ $cluster.name }}-cluster-pull-secret

---
apiVersion: cluster.open-cluster-management.io/v1
kind: ManagedCluster
metadata:
  labels:
    name: {{ $cluster.name }}
    vendor: OpenShift
    cluster.open-cluster-management.io/clusterset: {{ $clusterSet }}
    clusterGroup: {{ $clusterSet }}
    purpose: regionalDR
  name: {{ $cluster.name }}
spec:
  hubAcceptsClient: true

---
apiVersion: agent.open-cluster-management.io/v1
kind: KlusterletAddonConfig
metadata:
  name: {{ $cluster.name }}
  namespace: {{ $cluster.name }}
spec:
  clusterName: {{ $cluster.name }}
  clusterNamespace: {{ $cluster.name }}
  clusterLabels:
    vendor: OpenShift
  applicationManager:
    enabled: true
  policyController:
    enabled: true
  searchCollector:
    enabled: true
  certPolicyController:
    enabled: true
  iamPolicyController:
    enabled: true
{{- end }}
{{- end }}
