{{- range .Values.regionalDR }}
---
apiVersion: agent.open-cluster-management.io/v1
kind: KlusterletAddonConfig
metadata:
  name: {{ .primary }}
  namespace: {{ .primary }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  applicationManager:
    enabled: true
  certPolicyController:
    enabled: true
  iamPolicyController:
    enabled: true
  policyController:
    enabled: true
  searchCollector:
    enabled: true

{{- range .secondaries }}
---
apiVersion: agent.open-cluster-management.io/v1
kind: KlusterletAddonConfig
metadata:
  name: {{ . }}
  namespace: {{ . }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  applicationManager:
    enabled: true
  certPolicyController:
    enabled: true
  iamPolicyController:
    enabled: true
  policyController:
    enabled: true
  searchCollector:
    enabled: true

{{- end }}
{{- end }}
