{{- range .Values.regionalDR }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    operators.coreos.com/odr-hub-operator.openshift-dr-system: ""
  name: ramen-hub-operator-config
  namespace: openshift-operators
data:
  ramen_manager_config.yaml: |
    apiVersion: ramendr.openshift.io/v1alpha1
    kind: RamenConfig
    health:
      healthProbeBindAddress: :8081
    metrics:
      bindAddress: 127.0.0.1:9289
    webhook:
      port: 9443
    leaderElection:
      leaderElect: true
      resourceName: hub.ramendr.openshift.io
    ramenControllerType: dr-hub
    s3StoreProfiles:
    - s3ProfileName: s3profile-{{ .primary.name }}-ocs-storagecluster
      s3CompatibleEndpoint: {{ .primary.s3CompatibleEndpoint }}
      s3Region: {{ .primary.region }}
      s3Bucket: odrbucket-{{ .primary.name }}
      s3SecretRef:
        name: aws-secret
        namespace: {{ .primary.name }}
{{- range .secondaries }}
    - s3ProfileName: s3profile-{{ .name }}-ocs-storagecluster
      s3CompatibleEndpoint: {{ .s3CompatibleEndpoint }}
      s3Region: {{ .region }}
      s3Bucket: odrbucket-{{ .name }}
      s3SecretRef:
        name: aws-secret
        namespace: {{ .name }}
{{- end }}
    maxConcurrentReconciles: 50
    drClusterOperator:
      deploymentAutomationEnabled: true
      s3SecretDistributionEnabled: true
      channelName: stable-4.13
      packageName: odr-cluster-operator
      namespaceName: openshift-dr-system
      catalogSourceName: redhat-operators
      catalogSourceNamespaceName: openshift-marketplace
      clusterServiceVersionName: odr-cluster-operator.v4.13.7-rhodf
    kubeObjectProtection:
      disabled: true
{{- end }}
