{{- range .Values.regionalDR }}
{{- $dr := . }}

{{- range .Values.clusterGroup.managedClusterGroups }}
{{- $group := . }}
{{- if $group.clusterPools }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ $group.name }}-broker
---
apiVersion: submariner.io/v1alpha1
kind: Broker
metadata:
  name: submariner-broker
  namespace: {{ $group.name }}-broker
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  globalnetEnabled: {{ $dr.globalnetEnabled | default false }}

{{- end }}{{- /* if $group.clusterPools */}}
{{- end }}{{- /* range .Values.clusterGroup.managedClusterGroups */}}

---
apiVersion: addon.open-cluster-management.io/v1alpha1
kind: ManagedClusterAddOn
metadata:
  name: submariner
  namespace: {{ $dr.primary }}
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  installNamespace: submariner-operator
---
apiVersion: submarineraddon.open-cluster-management.io/v1alpha1
kind: SubmarinerConfig
metadata:
  name: submariner
  namespace: {{ $dr.primary }}
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  gatewayConfig:
    gateways: 1
    aws:
      instanceType: c5d.large
  IPSecNATTPort: 4500
  NATTEnable: true
  cableDriver: libreswan
  credentialsSecret:
    name: aws-secret

{{- range $dr.secondaries }}
{{- $secondary := . }}
---
apiVersion: addon.open-cluster-management.io/v1alpha1
kind: ManagedClusterAddOn
metadata:
  name: submariner
  namespace: {{ $secondary }}
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  installNamespace: submariner-operator
---
apiVersion: submarineraddon.open-cluster-management.io/v1alpha1
kind: SubmarinerConfig
metadata:
  name: submariner
  namespace: {{ $secondary }}
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  gatewayConfig:
    gateways: 1
    aws:
      instanceType: c5d.large
  IPSecNATTPort: 4500
  NATTEnable: true
  cableDriver: libreswan
  credentialsSecret:
    name: aws-secret

{{- end }}{{- /* range .secondaries */}}
{{- end }}{{- /* range .Values.regionalDR */}}
