{{- range .Values.regionalDR }}
{{ $clusterSet := .name }}
---
apiVersion: multicluster.odf.openshift.io/v1alpha1
kind: MirrorPeer
metadata:
  name: mirrorpeer-{{ $clusterSet }}
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  items:
  - clusterName: {{ .clusters.primary.name }}
    storageClusterRef:
      name: ocs-storagecluster
      namespace: openshift-storage
  - clusterName: {{ .clusters.secondary.name }}
    storageClusterRef:
      name: ocs-storagecluster
      namespace: openshift-storage
  manageS3: true
  schedulingIntervals:
    {{- toYaml .intervals | nindent 2 }}
  type: async
{{- end }}
