{{- range .Values.regionalDR }}
{{ $clusterSet := .name }}
---
apiVersion: multicluster.odf.openshift.io/v1alpha1
kind: MirrorPeer
metadata:
  name: mirrorpeer-{{ $clusterSet }}-{{ with (index .clusters.name 0) }}-{{ with (index .clusters.name 1) }}
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  items:
  - clusterName: {{ with (index .clusters.name 0) }}
    storageClusterRef:
      name: ocs-storagecluster
      namespace: openshift-storage
  - clusterName: {{ with (index .clusters.name 1) }}
    storageClusterRef:
      name: ocs-storagecluster
      namespace: openshift-storage
  manageS3: true
  schedulingIntervals:
    {{- toYaml .intervals | nindent 2 }}
  type: async
{{- end }}
