{{- range .Values.regionalDR }}
{{ $rdrName := .name }}
{{ $primary := .primary }}
{{- range .secondaries }}
---
apiVersion: multicluster.odf.openshift.io/v1alpha1
kind: MirrorPeer
metadata:
  name: mirrorpeer-{{ $rdrName }}-{{ $primary }}-{{ .name }}
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  items:
  - clusterName: {{ $primary }}
    storageClusterRef:
      name: ocs-storagecluster
      namespace: openshift-storage
  - clusterName: {{ . }}
    storageClusterRef:
      name: ocs-storagecluster
      namespace: openshift-storage
  manageS3: true
  schedulingIntervals:
  - 2m
  - 5m
  - 15m
  type: async
{{- end }}
{{- end }}
