{{- range .Values.regionalDR }}
{{ $clusterSet := .name }}
---
apiVersion: multicluster.odf.openshift.io/v1alpha1
kind: MirrorPeer
metadata:
  name: mirrorpeer-{{ $clusterSet }}
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  items:
  {{- with (index .clusters 0) }}
  - clusterName: {{ .name }}
  {{- end }}
    storageClusterRef:
      name: ocs-storagecluster
      namespace: openshift-storage
  {{- with (index .clusters 1) }}
  - clusterName: {{ .name }}
  {{- end }}
    storageClusterRef:
      name: ocs-storagecluster
      namespace: openshift-storage
  manageS3: true
  schedulingIntervals:
    {{- toYaml .intervals | nindent 2 }}
  type: async
{{- end }}
