{{- range .Values.regionalDR }}
---
apiVersion: submariner.io/v1alpha1
kind: Broker
metadata:
  name: submariner-broker
  namespace: {{ .name }}-broker
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  globalnetEnabled: {{ .globalnetEnabled | default false }}

---
apiVersion: addon.open-cluster-management.io/v1alpha1
kind: ManagedClusterAddOn
metadata:
  name: submariner
  namespace: {{ .primary.name }}
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  installNamespace: submariner-operator
---
apiVersion: submarineraddon.open-cluster-management.io/v1alpha1
kind: SubmarinerConfig
metadata:
  name: submariner
  namespace: {{ .primary.name }}
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  gatewayConfig:
    gateways: 1
    aws:
      instanceType: c5d.large
  IPSecNATTPort: 4500
  NATTEnable: true
  cableDriver: libreswan
  credentialsSecret:
    name: aws-secret

{{- range .secondaries }}
---
apiVersion: addon.open-cluster-management.io/v1alpha1
kind: ManagedClusterAddOn
metadata:
  name: submariner
  namespace: {{ .name }}
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  installNamespace: submariner-operator
---
apiVersion: submarineraddon.open-cluster-management.io/v1alpha1
kind: SubmarinerConfig
metadata:
  name: submariner
  namespace: {{ .name }}
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  gatewayConfig:
    gateways: 1
    aws:
      instanceType: c5d.large
  IPSecNATTPort: 4500
  NATTEnable: true
  cableDriver: libreswan
  credentialsSecret:
    name: aws-secret

{{- end }}
{{- end }}
